### ISSUE TITLE
Call setup_method & teardown_method on each re-run

### ISSUE THREAD

**Issue by mangeld** [box/flaky#64] opened 2015-10-21 15:45 UTC
If using the setup_class or setup_method to prepare fixtures for a test (like opening a browser in the setup_method and closing it in the teardown_method) should not flaky call those methods aswell on each run?

It might be related with #53

~~~ python
@flaky(min_passes=3, max_runs=6)
class TestFlaky:

    def setup_method(self, method):
        # It's called once
        pass

    def teardown_method(self, method):
        # Called once as well
        pass

    def test_fail_always(self):
        assert None
~~~

**Comment by emperorcezar** [comment] 2015-10-30 03:11
Without this, using flaky with live server tests in Django doesn't work as the server is never tore down.

**Comment by Jeff-Meadows** [comment] 2015-11-05 19:41
Yes, I think it's a duplicate of #53. I'll give that issue another shot at fixing. Not sure how easily it can be done.

**Closed by Jeff-Meadows** 2015-11-05 19:41 UTC
